services:
  - type: web
    name: bora-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://ara100limite:ERxkG9nXZjbwvpMk@cluster0.yzf2r.mongodb.net/bora?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: bora_uber_clone_secret_2024
      - key: PORT
        value: 5000
      - key: FRONTEND_URL
        value: https://seu-app.vercel.app # você vai substituir depois que criar na Vercel 