services:
  - type: web
    name: bora-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://ara100limite:ERxkG9nXZjbwvpMk@cluster0.yzf2r.mongodb.net/bora?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: bora_uber_clone_secret_2024
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://vextrix.vercel.app
      - key: CORS_ENABLED
        value: "true"
      - key: CORS_ORIGINS
        value: "https://vextrix.vercel.app,https://bora-frontend.vercel.app,http://localhost:3000"
      - key: TRUST_PROXY
        value: "true"